// <auto-generated />
namespace APIdotNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Vote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vote));
        
        string IMigrationMetadata.Id
        {
            get { return "202001161255522_Vote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
